---

- ansible.builtin.include_tasks: install-mysql-server.yml
  when: tuleap_conf_file.stat.exists == False

- ansible.builtin.include_tasks: install-tuleap_setup.yml
  when: tuleap_conf_file.stat.exists == False

...
