---

- name: Add Tuleap specific configuration
  copy:
    src: tuleap.cnf
    dest: "{{ mysql_config_path }}/my.cnf.d/tuleap.cnf"
    owner: root
    group: root
    mode:  0644

- name: Start mysql
  systemd:
    name: "{{ mysql_service }}"
    state: started
    enabled: yes

- name: Change mysql root password
  shell: |
    {{ mysql_bin_path }}/mysql -u root -NBe 'ALTER USER root@localhost IDENTIFIED WITH mysql_native_password BY {{ mysql_root_password | to_json(ensure_ascii=False) }}; FLUSH PRIVILEGES;';
