---
# Main Tuleap task list
- name: Check the OS major version
  ansible.builtin.fail:
    msg: "This tool supports only RedHat/CentOS after version 6. You use {{ ansible_os_family }} {{ ansible_distribution_major_version }}."
  when: ansible_os_family != "RedHat" or ansible_distribution_major_version|int <= 6

- name: Gather installed packages
  ansible.builtin.package_facts:
    manager: auto

- ansible.builtin.include_tasks: selinux.yml
- ansible.builtin.include_tasks: repositories.yml
- ansible.builtin.include_tasks: tuleap_packages.yml
- ansible.builtin.include_tasks: mail-server.yml

- ansible.builtin.include_tasks: firewalld.yml
  when: "'firewalld' in ansible_facts.packages"

- name: Check if this is a new Tuleap install
  ansible.builtin.stat:
    path: /etc/tuleap/conf/local.inc
  register: tuleap_conf_file

- ansible.builtin.include_tasks: install.yml
  when: tuleap_conf_file.stat.exists == False

- ansible.builtin.include_tasks: letsencrypt_cert.yml
  when: tuleap_generate_le_cert == True
