---
# Install Tuleap prerequisites

- name: Setup dependencies repositories
  ansible.builtin.package:
    name:
      - epel-release
      - https://rpms.remirepo.net/enterprise/remi-release-{{ ansible_distribution_major_version }}.rpm
    state: "{{ tuleap_packages_state }}"

- name: Install Tuleap repository
  ansible.builtin.copy:
    src: tuleap.repo
    dest: /etc/yum.repos.d/tuleap.repo
    owner: root
    group: root
    mode:  0644
