---
# Install Tuleap prerequisites

- name: Add GPG keys
  ansible.builtin.rpm_key:
    key: "{{ item }}"
  loop:
    - "{{ remi_repo_base_url }}/enterprise/{{ ansible_distribution_major_version }}/RPM-GPG-KEY-remi"
    - "{{ tuleap_repo_url }}/gpg.key"

- name: Setup dependencies repositories
  ansible.builtin.package:
    name:
      - epel-release
      - centos-release-scl
      - "{{ remi_repo_base_url }}/enterprise/remi-release-7.rpm"
      - "{{ tuleap_repo_url }}/rhel/7/dev/x86_64/tuleap-{{ tuleap_edition }}-release.rpm"
    state: "{{ tuleap_packages_state }}"

- name: Overload the repo source
  replace:
    path: /etc/yum.repos.d/tuleap.repo
    regexp: 'https://ci\.tuleap\.net/yum/tuleap'
    replace: "{{ tuleap_repo_url }}"
    backup: true
  when: tuleap_repo_url != 'https://ci.tuleap.net/yum/tuleap'
