---
# Install Tuleap prerequisites

- name: Add GPG keys
  ansible.builtin.rpm_key:
    key: "{{ item }}"
  loop:
    - "{{ remi_repo_base_url }}/enterprise/{{ ansible_distribution_major_version }}/RPM-GPG-KEY-remi"
    - "{{ tuleap_repo_url }}/gpg.key"

- name: Setup dependencies repositories
  ansible.builtin.package:
    name:
      - epel-release
      - "{{ remi_repo_base_url }}/enterprise/remi-release-{{ ansible_distribution_major_version }}.rpm"
      - "{{ tuleap_repo_url }}/rhel/{{ ansible_distribution_major_version }}/dev/{{ ansible_architecture }}/tuleap-{{ tuleap_edition }}-release.rpm"
    state: "{{ tuleap_packages_state }}"

- name: Overload the repo source
  replace:
    path: /etc/yum.repos.d/tuleap.repo
    regexp: 'https://ci\.tuleap\.net/yum/tuleap'
    replace: "{{ tuleap_repo_url }}"
    backup: true
  when: tuleap_repo_url != 'https://ci.tuleap.net/yum/tuleap'

- name: Add repository credentials if required
  ansible.builtin.lineinfile:
    path: /etc/yum.repos.d/tuleap.repo
    line: "{{ item }}"
    state: present
    mode: "o-rw"
  loop:
    - "username={{ tuleap_repo_user }}"
    - "password={{ tuleap_repo_password }}"
  when: tuleap_repo_user is defined

...
